module.exports = {

    Admin:{
        Resources:
        [
            "user",
            "role",
            "post",
            "project",
            "blog",
            "comment",
        ],
        Actions:
        [
            "write",
            "read",
            "delete",
            "manage",
            "update",
            "block",
            "follow",
            "ban",
        ],
    },
    Member:{
        Resources:
        [
            "post",
            "project",
            "blog",
            "comment",
        ],
        Actions:
        [
            "write",
            "read",
            "follow",
            "block",
        ],
    },
    Anon:{
        Resources:
        [
            "post",
            "project",
            "blog",
            "comment",
        ],
        Actions:
        [
            "write",
            "read",
        ],
    },
}