module.exports = {

    Admin:{
        Resources:
        [
            "users",
            "roles",
            "posts",
            "projects",
            "blogs",
            "comments",
        ],
        Actions:
        [
            "write",
            "read",
            "delete",
            "manage",
            "update",
            "block",
            "follow",
            "ban",
        ],
    },
    Member:{
        Resources:
        [
            "posts",
            "projects",
            "blogs",
            "comments",
        ],
        Actions:
        [
            "write",
            "read",
            "follow",
            "block",
        ],
    },
    Anon:{
        Resources:
        [
            "posts",
            "projects",
            "blogs",
            "comments",
        ],
        Actions:
        [
            "write",
            "read",
        ],
    },
}